### ISSUE TITLE
Add first name of Pazderka

### ISSUE THREAD

**Issue by butchcom** [TheRealVira/CentimeterBot#1]
The title page of the 'duties record book' lists the names of all people associated with the projects. Everyone is mentioned with his/her first name, except Pazderka. I think, his name should be added as well.

**Comment by TheRealVira** [comment]
As you may see - we are currently all over the documentation. If it is finished, we'll inform everyone by putting the information inside the readme file...

Please also note, that we might change to agile workstyle using scrum (and therefore some scrum integration - "ZenHub" as example), so it will be also easier for everyone who doesn't have the insights!

**Comment by butchcom** [comment]
Fair enough, thanks for the response. i just wanted to point this irregularity out. ZenHub is a very good PM option, but it does collide a bit with waffle.io. Personally, I'd recommend the first one.

Will @MaxiSchmid and @7rmccarthy  be able to handle the agile process? 😏

**Comment by TheRealVira** [comment]
Fixed: a74fda3aa57487546222c9b593347974d092200b
